version: '3'

services:
  todolistservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  todolistwebapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
