apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: todo-app
  type: LoadBalancer
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: todo-app
spec:
  replicas: 3
  selector:
    app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: mckdemo.azurecr.io/todolistwebapp:latest
        ports:
        - containerPort: 80
          protocol: TCP
	  imagePullSecrets:
		- name: mck-demo-registry
